version: "3"
services:
  stablefusion_db:
    image: mongo
    container_name: stablefusion_db
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  stablefusion_app:
    build: .
    container_name: stablefusion_app
    restart: on-failure
    volumes:
      - ./storages/gallery:/app/storage/gallery
      - ./storages/selfies:/app/storage/selfies
    ports:
      - 80:80
      - 443:443
    depends_on:
      - stablefusion_db
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://db:27017/mern
